[package]
name = "vban_autogain"
version = "0.1.0"
authors = ["c000 <chikusat@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "0.99.*"
byteorder = "1.3.*"
clap = "2.33.*"
